### ISSUE TITLE
Loading in Loop

### ISSUE THREAD

**Issue by joaogolias** [davicorreiajr/spotify-now-playing#1]
I have downloaded the DMG file and tried to use it in a MacBook Air (with Majove Version 10.4)
Firstly, I could see nothing but the loading gif and, suddenly, it has been gone and the View has gotten very smaller. 
![screen shot 2018-11-22 at 10 13 07](https://user-images.githubusercontent.com/38192396/48902350-764e6680-ee3f-11e8-936a-e7c72ac41a27.png)

Then, I cloned the project,  set the environment (following the step-by-step, in READ.me), and decided to increase the size of the View (by increasing the variables WINDOW_WIDTH and WINDOW_HEIGHT and commenting the fixWindowHeight() function). I noticed that the loading gif was there yet.
![screen shot 2018-11-22 at 10 19 10](https://user-images.githubusercontent.com/38192396/48902566-15735e00-ee40-11e8-8d98-85d52d719b8d.png)

With Google Inspector Tools, I tried to see any logged errors, including network ones. But, as you can see, there is nothing besides a warning
![screen shot 2018-11-22 at 10 21 22](https://user-images.githubusercontent.com/38192396/48902671-671be880-ee40-11e8-91e0-761b6f69483f.png)

Furthermore, I accidentally clicked on Inspector 'Performance' icon, and an error appeared in my shell terminal:
![screen shot 2018-11-22 at 10 23 38](https://user-images.githubusercontent.com/38192396/48902754-b235fb80-ee40-11e8-822e-e77532329f73.png)

**Comment by davicorreiajr** [comment]
Thanks for submitting the issue!

There was a problem with the Spotify scopes. I fixed the problems and you can re-download the app from the [latest release](https://github.com/davicorreiajr/spotify-now-playing/releases/latest).
