### ISSUE TITLE
Feature requests & suggestions

### ISSUE THREAD

**Issue by Aerozolic** [davicorreiajr/spotify-now-playing#2]
Hi!

Thanks for developing this. Here are my suggestions/requests that first came to mind:

- If Spotify is not running then clicking play would open Spotify and start playing the song

- Clicking on the artwork should act the same way as clicking on the artwork in Spotify app

- Add more icons from Spotify's now playing screen (repeat, shuffle and so on)

- Maybe it's because of my non-retina screen but the app icon could use a bit more work. ![screen shot 2018-11-25 at 16 10 15](https://user-images.githubusercontent.com/25500346/48980054-cb52dc80-f0cc-11e8-8a04-3bf8b2bfb5cd.png)

- The app reacts a bit slowly to commands and song changes

- Maybe add a bit of animations to the icons like Spotify app has (when hovering over icons and when clicking on icons)

Thanks!

**Comment by davicorreiajr** [comment]
Hello!

Thank you so much for your feedback :) I think they could be good improvements for the app. For now, I just released another version where I fix some problems, including the icon size you mentioned.

I'll keep the issue open, so I can remember to implement some of those soon.

**Comment by davicorreiajr** [comment]
hey @Aerozolic, @bressan3 just implemented the shuffle option!
