### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by 3raxton** [davicorreiajr/spotify-now-playing#33]
# I just wanted to say thanks

There are a lot of apps that provide for the ability to view Spotify from the menu bar but *none* that allow for users to add a song to their playlist which I've been looking for - forever. 

## I wanted to express my appreciation for this feature and app which is rich in features and maintained. Keep up the great work! 🎉

**Comment by davicorreiajr** [comment]
Thank you so much :) It's really great to read this!

And for sure, this project can still grow a lot, if more people contribute, but mainly, use the app. Thanks a lot again!!
